name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.23.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Build
        env:
          GOOS: 'linux'
          GOARCH: 'amd64'
        run: | 
          go build -o mqtt_consumer_db ./main.go
      - name: Archive artifacts
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: mqtt_consumer_db
          path: mqtt_consumer_db